export const Characters=[
	{
	Character:'喂',
	Tradiional:'',
	Pronounciation:'wèi',
	Meaning:'hello (on the phone)',
	Category:'Expression'
	},

	{
	Character:'谢谢',
	Tradiional:'',
	Pronounciation:'xièxie',
	Meaning:'thanks',
	Category:'Expression'
	},
	{
	Character:'不客气',
	Tradiional:'',
	Pronounciation:'bú kèqi ',
	Meaning:'you’re welcome',
	Category:'Expression'
	},

	{
	Character:'再见',
	Tradiional:'',
	Pronounciation:'zàijiàn',
	Meaning:'goodbye',
	Category:'Expression'
	},
	{
	Character:'请',
	Tradiional:'',
	Pronounciation:'qǐng',
	Meaning:'please',
	Category:'Expression'
	},
	{
	Character:'对不起',
	Tradiional:'',
	Pronounciation:'duìbuqǐ',
	Meaning:'sorry',
	Category:'Expression'
	},
	{
	Character:'没关系',
	Tradiional:'',
	Pronounciation:'méi guānxi',
	Meaning:'it’s all right',
	Category:'Expression'
	},
	{
	Character:'和',
	Tradiional:'',
	Pronounciation:'hé',
	Meaning:'and',
	Category:'Conjunction'
	},
	{
	Character:'的',
	Tradiional:'',
	Pronounciation:'de',
	Meaning:'possession particle',
	Category:'Particle'
	},
	{
	Character:'了',
	Tradiional:'',
	Pronounciation:'le',
	Meaning:'aspect particle',
	Category:'Particle'
	},
	{
	Character:'吗',
	Tradiional:'',
	Pronounciation:'ma',
	Meaning:'question particle',
	Category:'Particle'
	},
	{
	Character:'呢',
	Tradiional:'',
	Pronounciation:'ne',
	Meaning:'question particle',
	Category:'Particle'
	},	
	{
	Character:'好',
	Tradiional:'',
	Pronounciation:'hǎo',
	Meaning:'good',
	Category:'Adjectives/Adverbs'
	},
	{
	Character:'大',
	Tradiional:'',
	Pronounciation:'dà',
	Meaning:'big',
	Category:'Adjectives/Adverbs'
	},
	{
	Character:'小',
	Tradiional:'',
	Pronounciation:'xiǎo',
	Meaning:'small',
	Category:'Adjectives/Adverbs'
	},
	{
	Character:'多',
	Tradiional:'',
	Pronounciation:'duō',
	Meaning:'many',
	Category:'Adjectives/Adverbs'
	},
	{
	Character:'少',
	Tradiional:'',
	Pronounciation:'shǎo',
	Meaning:'few',
	Category:'Adjectives/Adverbs'
	},	
	{
	Character:'热',
	Tradiional:'',
	Pronounciation:'rè',
	Meaning:'hot',
	Category:'Adjectives/Adverbs'
	},
	{
	Character:'冷',
	Tradiional:'',
	Pronounciation:'lěng',
	Meaning:'cold',
	Category:'Adjectives/Adverbs'
	},
	{
	Character:'漂亮',
	Tradiional:'',
	Pronounciation:'piàoliang',
	Meaning:'pretty',
	Category:'Adjectives/Adverbs'
	},
	{
	Character:'高兴',
	Tradiional:'',
	Pronounciation:'gāoxìng',
	Meaning:'happy',
	Category:'Adjectives/Adverbs'
	},
	{
	Character:'很',
	Tradiional:'',
	Pronounciation:'hěn',
	Meaning:'very',
	Category:'Adjectives/Adverbs'
	},	
	{
	Character:'太',
	Tradiional:'',
	Pronounciation:'tài',
	Meaning:'too...',
	Category:'Adjectives/Adverbs'
	},	
	{
	Character:'都',
	Tradiional:'',
	Pronounciation:'dōu',
	Meaning:'both or all',
	Category:'Adjectives/Adverbs'
	},	
	{
	Character:'不',
	Tradiional:'',
	Pronounciation:'bù',
	Meaning:'not',
	Category:'Adjectives/Adverbs'
	},	
	{
	Character:'没',
	Tradiional:'',
	Pronounciation:'méi',
	Meaning:'not',
	Category:'Adjectives/Adverbs'
	},	
	{
	Character:'个',
	Tradiional:'',
	Pronounciation:'gè',
	Meaning:'generic measure word',
	Category:'Measure Word'
	},	
	{
	Character:'块',
	Tradiional:'',
	Pronounciation:'kuài',
	Meaning:'basic monetary unit of China',
	Category:'Measure Word'
	},	
	{
	Character:'本',
	Tradiional:'',
	Pronounciation:'běn',
	Meaning:'for books',
	Category:'Measure Word'
	},	
	{
	Character:'岁',
	Tradiional:'',
	Pronounciation:'suì',
	Meaning:'year (of age)',
	Category:'Measure Word'
	},	
	{
	Character:'些',
	Tradiional:'',
	Pronounciation:'xiē',
	Meaning:'some',
	Category:'Measure Word'
	},	
	{
	Character:'做',
	Tradiional:'',
	Pronounciation:'zuò',
	Meaning:'to do',
	Category:'Verb'
	},	
	{
	Character:'是',
	Tradiional:'',
	Pronounciation:'shì',
	Meaning:'to be',
	Category:'Verb'
	},																											
	{
	Character:'在',
	Tradiional:'',
	Pronounciation:'zài',
	Meaning:'to be in',
	Category:'Verb'
	},	
	{
	Character:'有',
	Tradiional:'',
	Pronounciation:'yǒu',
	Meaning:'to have',
	Category:'Verb'
	},	
	{
	Character:'住',
	Tradiional:'',
	Pronounciation:'zhù',
	Meaning:'to live or to stay',
	Category:'Verb'
	},	
	{
	Character:'来',
	Tradiional:'',
	Pronounciation:'lái',
	Meaning:'to come',
	Category:'Verb'
	},	
	{
	Character:'去',
	Tradiional:'',
	Pronounciation:'qù',
	Meaning:'to go',
	Category:'Verb'
	},	
	{
	Character:'回',
	Tradiional:'',
	Pronounciation:'huí',
	Meaning:'to return',
	Category:'Verb'
	},	
	{
	Character:'想',
	Tradiional:'',
	Pronounciation:'xiǎng',
	Meaning:'to think',
	Category:'Verb'
	},	
	{
	Character:'吃',
	Tradiional:'',
	Pronounciation:'chī',
	Meaning:'to eat',
	Category:'Verb'
	},	
	{
	Character:'喝',
	Tradiional:'',
	Pronounciation:'hē',
	Meaning:'to drink',
	Category:'Verb'
	},	
	{
	Character:'说话',
	Tradiional:'',
	Pronounciation:'shuōhuà',
	Meaning:'to speak',
	Category:'Verb'
	},	
	{
	Character:'看',
	Tradiional:'',
	Pronounciation:'kàn',
	Meaning:'to look or to watch',
	Category:'Verb'
	},	
	{
	Character:'看见',
	Tradiional:'',
	Pronounciation:'kànjiàn',
	Meaning:'to see',
	Category:'Verb'
	},	
	{
	Character:'听',
	Tradiional:'',
	Pronounciation:'tīng',
	Meaning:'to listen',
	Category:'Verb'
	},	
	{
	Character:'叫',
	Tradiional:'',
	Pronounciation:'jiào',
	Meaning:'to call',
	Category:'Verb'
	},	
	{
	Character:'买',
	Tradiional:'',
	Pronounciation:'mǎi',
	Meaning:'to buy',
	Category:'Verb'
	},	
	{
	Character:'开',
	Tradiional:'',
	Pronounciation:'kāi',
	Meaning:'to drive or to open',
	Category:'Verb'
	},	
	{
	Character:'坐',
	Tradiional:'',
	Pronounciation:'zuò',
	Meaning:'to sit',
	Category:'Verb'
	},	
	{
	Character:'读',
	Tradiional:'',
	Pronounciation:'dú',
	Meaning:'to read',
	Category:'Verb'
	},	
	{
	Character:'写',
	Tradiional:'',
	Pronounciation:'xiě',
	Meaning:'to write',
	Category:'Verb'
	},	
	{
	Character:'打电话',
	Tradiional:'',
	Pronounciation:'dǎ diànhuà',
	Meaning:'to make a phone call',
	Category:'Verb'
	},	
	{
	Character:'认识',
	Tradiional:'',
	Pronounciation:'rènshi',
	Meaning:'to know',
	Category:'Verb'
	},	
	{
	Character:'学习',
	Tradiional:'',
	Pronounciation:'xuéxí',
	Meaning:'to learn',
	Category:'Verb'
	},	
	{
	Character:'工作',
	Tradiional:'',
	Pronounciation:'gōngzuò',
	Meaning:'to work',
	Category:'Verb'
	},	
	{
	Character:'睡觉',
	Tradiional:'',
	Pronounciation:'shuìjiào',
	Meaning:'to sleep',
	Category:'Verb'
	},	
	{
	Character:'喜欢',
	Tradiional:'',
	Pronounciation:'xǐhuan',
	Meaning:'to like',
	Category:'Verb'
	},	
	{
	Character:'爱',
	Tradiional:'',
	Pronounciation:'ài',
	Meaning:'to love',
	Category:'Verb'
	},	
	{
	Character:'会',
	Tradiional:'',
	Pronounciation:'huì',
	Meaning:'can (to know how to)',
	Category:'Verb'
	},	
	{
	Character:'能',
	Tradiional:'',
	Pronounciation:'néng',
	Meaning:'can (to be able to)',
	Category:'Verb'
	},	
	{
	Character:'下雨',
	Tradiional:'',
	Pronounciation:'xià yǔ',
	Meaning:'to rain',
	Category:'Verb'
	},	
	{
	Character:'中国',
	Tradiional:'',
	Pronounciation:'Zhōngguó',
	Meaning:'China',
	Category:'Places'
	},		
	{
	Character:'北京',
	Tradiional:'',
	Pronounciation:'Běijīng',
	Meaning:'Beijing',
	Category:'Places'
	},	
	{
	Character:'家',
	Tradiional:'',
	Pronounciation:'jiā',
	Meaning:'home or family',
	Category:'Places'
	},	
	{
	Character:'学校',
	Tradiional:'',
	Pronounciation:'xuéxiào',
	Meaning:'school',
	Category:'Places'
	},	
	{
	Character:'饭馆',
	Tradiional:'',
	Pronounciation:'fànguǎn',
	Meaning:'restaurant',
	Category:'Places'
	},	
	{
	Character:'商店',
	Tradiional:'',
	Pronounciation:'shāngdiàn',
	Meaning:'shop',
	Category:'Places'
	},	
	{
	Character:'医院',
	Tradiional:'',
	Pronounciation:'yīyuàn',
	Meaning:'hospital',
	Category:'Places'
	},	
	{
	Character:'火车站',
	Tradiional:'',
	Pronounciation:'huǒchēzhàn',
	Meaning:'train station',
	Category:'Places'
	},	
	{
	Character:'上',
	Tradiional:'',
	Pronounciation:'shàng',
	Meaning:'on, above or last',
	Category:'Places'
	},	
	{
	Character:'下',
	Tradiional:'',
	Pronounciation:'xià',
	Meaning:'under, below or next',
	Category:'Places'
	},	
	{
	Character:'前面',
	Tradiional:'',
	Pronounciation:'qiánmiàn',
	Meaning:'front',
	Category:'Places'
	},	
	{
	Character:'后面',
	Tradiional:'',
	Pronounciation:'hòumiàn',
	Meaning:'back',
	Category:'Places'
	},	
	{
	Character:'里',
	Tradiional:'',
	Pronounciation:'lǐ',
	Meaning:'inside',
	Category:'Places'
	},	
	{
	Character:'人',
	Tradiional:'',
	Pronounciation:'rén',
	Meaning:'person or people',
	Category:'People/Things'
	},	
	{
	Character:'名字',
	Tradiional:'',
	Pronounciation:'míngzì',
	Meaning:'name',
	Category:'People/Things'
	},	
	{
	Character:'妈妈',
	Tradiional:'',
	Pronounciation:'māma',
	Meaning:'mom',
	Category:'People/Things'
	},	
	{
	Character:'爸爸',
	Tradiional:'',
	Pronounciation:'bàba',
	Meaning:'dad',
	Category:'People/Things'
	},	
	{
	Character:'儿子',
	Tradiional:'',
	Pronounciation:'érzi',
	Meaning:'son',
	Category:'People/Things'
	},	
	{
	Character:'女儿',
	Tradiional:'',
	Pronounciation:'nǚ’ér',
	Meaning:'daughter',
	Category:'People/Things'
	},	
	{
	Character:'朋友',
	Tradiional:'',
	Pronounciation:'péngyǒu',
	Meaning:'friend',
	Category:'People/Things'
	},	
	{
	Character:'先生',
	Tradiional:'',
	Pronounciation:'xiānsheng',
	Meaning:'Mr or sir',
	Category:'People/Things'
	},	
	{
	Character:'小姐',
	Tradiional:'',
	Pronounciation:'xiǎojiě',
	Meaning:'Miss',
	Category:'People/Things'
	},	
	{
	Character:'老师',
	Tradiional:'',
	Pronounciation:'lǎoshī',
	Meaning:'teacher',
	Category:'People/Things'
	},	
	{
	Character:'学生',
	Tradiional:'',
	Pronounciation:'xuésheng',
	Meaning:'student',
	Category:'People/Things'
	},		
	{
	Character:'同学',
	Tradiional:'',
	Pronounciation:'tóngxué',
	Meaning:'schoolmate',
	Category:'People/Things'
	},	
	{
	Character:'医生',
	Tradiional:'',
	Pronounciation:'yīshēng',
	Meaning:'doctor',
	Category:'People/Things'
	},	
	{
	Character:'东西',
	Tradiional:'',
	Pronounciation:'dōngxi',
	Meaning:'thing',
	Category:'People/Things'
	},	
	{
	Character:'钱',
	Tradiional:'',
	Pronounciation:'qián',
	Meaning:'money',
	Category:'People/Things'
	},	
	{
	Character:'水',
	Tradiional:'',
	Pronounciation:'shuǐ',
	Meaning:'water',
	Category:'People/Things'
	},	
	{
	Character:'茶',
	Tradiional:'',
	Pronounciation:'chá',
	Meaning:'tea',
	Category:'People/Things'
	},	
	{
	Character:'菜',
	Tradiional:'',
	Pronounciation:'cài',
	Meaning:'dish',
	Category:'People/Things'
	},	
	{
	Character:'米饭',
	Tradiional:'',
	Pronounciation:'mǐfàn',
	Meaning:'(cooked) rice',
	Category:'People/Things'
	},	
	{
	Character:'衣服',
	Tradiional:'',
	Pronounciation:'yīfu',
	Meaning:'clothes',
	Category:'People/Things'
	},	
	{
	Character:'书',
	Tradiional:'',
	Pronounciation:'shū',
	Meaning:'book',
	Category:'People/Things'
	},	
	{
	Character:'桌子',
	Tradiional:'',
	Pronounciation:'zhuōzi',
	Meaning:'table or desk',
	Category:'People/Things'
	},	
	{
	Character:'椅子',
	Tradiional:'',
	Pronounciation:'yǐzi',
	Meaning:'chair',
	Category:'People/Things'
	},	
	{
	Character:'水果',
	Tradiional:'',
	Pronounciation:'shuǐguǒ',
	Meaning:'fruit',
	Category:'People/Things'
	},	
	{
	Character:'苹果',
	Tradiional:'',
	Pronounciation:'píngguǒ',
	Meaning:'apple',
	Category:'People/Things'
	},	
	{
	Character:'杯子',
	Tradiional:'',
	Pronounciation:'bēizi',
	Meaning:'cup or glass',
	Category:'People/Things'
	},	
	{
	Character:'电视',
	Tradiional:'',
	Pronounciation:'diànshì',
	Meaning:'TV',
	Category:'People/Things'
	},	
	{
	Character:'电脑',
	Tradiional:'',
	Pronounciation:'diànnǎo',
	Meaning:'computer',
	Category:'People/Things'
	},	
	{
	Character:'电影',
	Tradiional:'',
	Pronounciation:'diànyǐng',
	Meaning:'movie',
	Category:'People/Things'
	},	
	{
	Character:'飞机',
	Tradiional:'',
	Pronounciation:'fēijī',
	Meaning:'plane',
	Category:'People/Things'
	},	
	{
	Character:'出租车',
	Tradiional:'',
	Pronounciation:'chūzūchē',
	Meaning:'taxi',
	Category:'People/Things'
	},	
	{
	Character:'猫',
	Tradiional:'',
	Pronounciation:'māo',
	Meaning:'cat',
	Category:'People/Things'
	},	
	{
	Character:'狗',
	Tradiional:'',
	Pronounciation:'gǒu',
	Meaning:'dog',
	Category:'People/Things'
	},	
	{
	Character:'天气',
	Tradiional:'',
	Pronounciation:'tiānqì',
	Meaning:'weather',
	Category:'People/Things'
	},	
	{
	Character:'字',
	Tradiional:'',
	Pronounciation:'zì',
	Meaning:'character',
	Category:'People/Things'
	},	
	{
	Character:'汉语',
	Tradiional:'',
	Pronounciation:'Hànyǔ',
	Meaning:'Chinese (language)',
	Category:'People/Things'
	},	
	{
	Character:'现在',
	Tradiional:'',
	Pronounciation:'xiànzài',
	Meaning:'now',
	Category:'Time'
	},	
	{
	Character:'今天',
	Tradiional:'',
	Pronounciation:'jīntiān',
	Meaning:'today',
	Category:'Time'
	},	
	{
	Character:'明天',
	Tradiional:'',
	Pronounciation:'míngtiān',
	Meaning:'tomorrow',
	Category:'Time'
	},	
	{
	Character:'昨天',
	Tradiional:'',
	Pronounciation:'zuótiān',
	Meaning:'yesterday',
	Category:'Time'
	},	
	{
	Character:'上午',
	Tradiional:'',
	Pronounciation:'shàngwǔ',
	Meaning:'morning',
	Category:'Time'
	},	
	{
	Character:'中午',
	Tradiional:'',
	Pronounciation:'zhōngwǔ',
	Meaning:'noon',
	Category:'Time'
	},	
	{
	Character:'下午',
	Tradiional:'',
	Pronounciation:'xiàwǔ',
	Meaning:'afternoon',
	Category:'Time'
	},	
	{
	Character:'点',
	Tradiional:'',
	Pronounciation:'diǎn',
	Meaning:'o’clock',
	Category:'Time'
	},	
	{
	Character:'分钟',
	Tradiional:'',
	Pronounciation:'fēnzhōng',
	Meaning:'minute',
	Category:'Time'
	},	
	{
	Character:'年',
	Tradiional:'',
	Pronounciation:'nián',
	Meaning:'year',
	Category:'Time'
	},	
	{
	Character:'月',
	Tradiional:'',
	Pronounciation:'yuè',
	Meaning:'month',
	Category:'Time'
	},	
	{
	Character:'日',
	Tradiional:'',
	Pronounciation:'rì',
	Meaning:'day',
	Category:'Time'
	},	
	{
	Character:'星期',
	Tradiional:'',
	Pronounciation:'xīngqī',
	Meaning:'week',
	Category:'Time'
	},	
	{
	Character:'时候',
	Tradiional:'',
	Pronounciation:'shíhou',
	Meaning:'a certain point in time',
	Category:'Time'
	},	
	{
	Character:'哪/哪儿',
	Tradiional:'',
	Pronounciation:'nǎ/nǎr',
	Meaning:'which/where',
	Category:'Question'
	},	
	{
	Character:'谁',
	Tradiional:'',
	Pronounciation:'shéi',
	Meaning:'who',
	Category:'Question'
	},	
	{
	Character:'什么',
	Tradiional:'',
	Pronounciation:'shénme',
	Meaning:'what',
	Category:'Question'
	},	
	{
	Character:'多少',
	Tradiional:'',
	Pronounciation:'duōshao',
	Meaning:'how many or how much',
	Category:'Question'
	},	
	{
	Character:'几',
	Tradiional:'',
	Pronounciation:'jǐ',
	Meaning:'how many or how much',
	Category:'Question'
	},	
	{
	Character:'怎么',
	Tradiional:'',
	Pronounciation:'zěnme',
	Meaning:'how',
	Category:'Question'
	},	
	{
	Character:'怎么样',
	Tradiional:'',
	Pronounciation:'zěnmeyàng',
	Meaning:'how about',
	Category:'Question'
	},	
	{
	Character:'我',
	Tradiional:'',
	Pronounciation:'wǒ',
	Meaning:'I or me',
	Category:'Pronouns'
	},	
	{
	Character:'你',
	Tradiional:'',
	Pronounciation:'nǐ',
	Meaning:'you (singular)',
	Category:'Pronouns'
	},	
	{
	Character:'他',
	Tradiional:'',
	Pronounciation:'tā',
	Meaning:'he or him',
	Category:'Pronouns'
	},	
	{
	Character:'她',
	Tradiional:'',
	Pronounciation:'tā',
	Meaning:'she or her',
	Category:'Pronouns'
	},	
	{
	Character:'我们',
	Tradiional:'',
	Pronounciation:'wǒmen',
	Meaning:'we or me',
	Category:'Pronouns'
	},	
	{
	Character:'这/这儿',
	Tradiional:'',
	Pronounciation:'zhè/zhèr',
	Meaning:'this/here',
	Category:'Pronouns'
	},	
	{
	Character:'那/那儿',
	Tradiional:'',
	Pronounciation:'nà/nàr',
	Meaning:'that/there',
	Category:'Pronouns'
	},	
	{
	Character:'零',
	Tradiional:'',
	Pronounciation:'líng',
	Meaning:'zero',
	Category:'Number'
	},	
	{
	Character:'一',
	Tradiional:'',
	Pronounciation:'yī',
	Meaning:'one',
	Category:'Number'
	},	
	{
	Character:'二',
	Tradiional:'',
	Pronounciation:'èr',
	Meaning:'two',
	Category:'Number'
	},	
	{
	Character:'三',
	Tradiional:'',
	Pronounciation:'sān',
	Meaning:'three',
	Category:'Number'
	},	
	{
	Character:'四',
	Tradiional:'',
	Pronounciation:'sì',
	Meaning:'four',
	Category:'Number'
	},	
	{
	Character:'五',
	Tradiional:'',
	Pronounciation:'wǔ',
	Meaning:'five',
	Category:'Number'
	},	
	{
	Character:'六',
	Tradiional:'',
	Pronounciation:'liù',
	Meaning:'six',
	Category:'Number'
	},	
	{
	Character:'七',
	Tradiional:'',
	Pronounciation:'qī',
	Meaning:'seven',
	Category:'Number'
	},	
	{
	Character:'八',
	Tradiional:'',
	Pronounciation:'bā',
	Meaning:'eight',
	Category:'Number'
	},	
	{
	Character:'九',
	Tradiional:'',
	Pronounciation:'jiǔ',
	Meaning:'nine',
	Category:'Number'
	},	
	{
	Character:'十',
	Tradiional:'',
	Pronounciation:'shí',
	Meaning:'ten',
	Category:'Number'
	},																																																																									
]